-- 创建数据库
CREATE DATABASE IF NOT EXISTS ai_interview DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ai_interview;

-- 角色表
CREATE TABLE IF NOT EXISTS role (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL UNIQUE COMMENT '角色名：普通用户、管理员',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 用户表
CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE COLLATE utf8mb4_bin,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) DEFAULT NULL,
  role_id INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES role(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 岗位表（position 为 MySQL 保留字，需反引号）
CREATE TABLE IF NOT EXISTS `position` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL COMMENT '如：后端、前端、算法',
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 题库表
CREATE TABLE IF NOT EXISTS question_bank (
  id INT AUTO_INCREMENT PRIMARY KEY,
  position_id INT NOT NULL,
  question TEXT NOT NULL COMMENT '面试题目',
  answer TEXT DEFAULT NULL COMMENT '参考答案',
  knowledge_tags VARCHAR(500) DEFAULT NULL COMMENT '知识点标签，逗号分隔或JSON',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (position_id) REFERENCES `position`(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 知识库文档表（文本块、向量ID）
CREATE TABLE IF NOT EXISTS knowledge_base (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL COMMENT '文本块内容',
  vector_id VARCHAR(100) DEFAULT NULL COMMENT '向量数据库中的ID',
  source_type VARCHAR(50) DEFAULT NULL COMMENT '来源类型：question_bank等',
  source_id INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 面试记录表
CREATE TABLE IF NOT EXISTS interview_record (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  position_id INT NOT NULL,
  started_at DATETIME NOT NULL,
  ended_at DATETIME DEFAULT NULL,
  total_score DECIMAL(5,2) DEFAULT NULL COMMENT '综合评分',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (position_id) REFERENCES `position`(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 面试对话详情表
CREATE TABLE IF NOT EXISTS interview_detail (
  id INT AUTO_INCREMENT PRIMARY KEY,
  interview_record_id INT NOT NULL,
  round_index INT NOT NULL COMMENT '轮次序号',
  role VARCHAR(20) NOT NULL COMMENT 'user|assistant',
  content TEXT NOT NULL COMMENT '问答内容',
  emotion_data JSON DEFAULT NULL COMMENT '情感数据',
  score DECIMAL(5,2) DEFAULT NULL COMMENT '单题评分',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (interview_record_id) REFERENCES interview_record(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 报告表（JSON格式）
CREATE TABLE IF NOT EXISTS report (
  id INT AUTO_INCREMENT PRIMARY KEY,
  interview_record_id INT NOT NULL UNIQUE,
  content JSON NOT NULL COMMENT '报告内容',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (interview_record_id) REFERENCES interview_record(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 学习资源表
CREATE TABLE IF NOT EXISTS learning_resource (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  link VARCHAR(500) NOT NULL,
  tags VARCHAR(500) DEFAULT NULL COMMENT '标签，逗号分隔或JSON',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 初始化角色
INSERT INTO role (id, name) VALUES (1, '普通用户'), (2, '管理员') ON DUPLICATE KEY UPDATE name=VALUES(name);

-- 初始化岗位示例
INSERT INTO `position` (id, name, sort_order) VALUES (1, 'Java后端', 1), (2, 'Web前端', 2), (3, '算法', 3) ON DUPLICATE KEY UPDATE name=VALUES(name), sort_order=VALUES(sort_order);
